source("Final Project.R")

shinyServer(function(input, output, session) {
  #output$pricePlot <- plotPriceChanges()
  #output$sizePlot <- plotSizeChanges()
  output$plotNorm <- plotNormalizedPrice()
  output$plotVarAccyy <- plotVarAccyy(input)
  output$plotVarDLAKY <- plotVarDLAKY(input)
  output$plotVarICAGY <- plotVarICAGY(input)
  output$plotVarIHG <- plotVarIHG(input)
  output$plotVarEUR <- plotVarEUR(input)
  output$plotVarGBP <- plotVarGBP(input)
  output$plotCorr <- plotCorr()
  output$plotDlakyIcagy <- plotDlakyIcagy(input)
  output$plotICAGYEuro <- plotICAGYEuro(input)
  output$plotMarkovSHort <- plotMarkovSHort()
  output$plotAllocation <- plotAllocation()
  output$plotMarkovNoShort <- plotMarkovNoShort()
  output$plotCumReturns <- plotCumReturns()
  output$plotDrawDown <- plotDrawDown()
  output$plotPriceChanges <- plotPriceChanges()
  output$plotPriceSizeChanges <- plotPriceSizeChanges()
  output$plotGPD <- plotGPD()
  output$plotExcessLoss <- plotExcessLoss()
  output$plotConf <- plotConf()
  output$plotRisk <- plotRisk()
  output$table <- renderDataTable(round(w_all, digits = 2))
})
